#
# Default configuration for the custom Kafka JSON event subscriber.
# These defaults can be overridden via Helm values (advancedConfig) or environment variables.
#

# Kafka JSON producer channel configuration
mp.messaging.outgoing.nessie-kafka-json.connector=smallrye-kafka
mp.messaging.outgoing.nessie-kafka-json.topic=nessie-events
mp.messaging.outgoing.nessie-kafka-json.value.serializer=org.projectnessie.events.custom.kafka.json.KafkaJsonEventSerializer
